version: '3.8'
services:
    db:
        container_name: pg_container
        image: postgres
        restart: always
        env_file:
            - docker.env
        ports:
            - '5432:5432'
