## TODO
# User nie ma daty urodzenia*
# UserCreationParams zmienić*
# Animal do zmiany dummy data
# Endpointy do zmiany
# 
 
### Get all animals
GET https://coders-camp-schronisko.herokuapp.com/api/animals

### Get animal
GET https://coders-camp-schronisko.herokuapp.com/api/animals/1

### Register user
POST https://coders-camp-schronisko.herokuapp.com/api/users
Content-Type: application/json

{
    "repPassword": "ZAQ!2wsx",
    "password": "ZAQ!2wsx",
    "mail": "elo@elo.elo"
}

### Activate user
GET https://coders-camp-schronisko.herokuapp.com/api/users/activate/32195d9c-a7cb-4931-94d7-65c67bce12b9

### Login user
POST https://coders-camp-schronisko.herokuapp.com/api/users/auth
Content-Type: application/json

{
    "mail": "elo@elo.elo",
    "password": "ZAQ!2wsx"
}

### Get adoption form
GET https://coders-camp-schronisko.herokuapp.com/api/forms/2
access_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoibm9ybWFsIiwiaWQiOjYsImlhdCI6MTYxNjUzNTI5M30.02-wBPGdYx-ewFkL6aIZqixstrauzC2OigOwRitwfMs

### Post adoption form
POST https://coders-camp-schronisko.herokuapp.com/api/adoptionSubmissions/add
access_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoibm9ybWFsIiwiaWQiOjYsImlhdCI6MTYxNjUzNTI5M30.02-wBPGdYx-ewFkL6aIZqixstrauzC2OigOwRitwfMs
Content-Type: application/json

{
    "animalId": 2,
    "stepNumber": 1,
    "answers": [
        {
            "questionId": 3,
            "answer": {
                "type": "checkbox",
                "answer": "Tak"
            }
        },
        {
            "questionId": 4,
            "answer": {
                "type": "checkbox",
                "answer": "Nie"
            }
        }
    ]
}

### Get user's submissions
GET https://coders-camp-schronisko.herokuapp.com/api/adoptionSubmissions/add